markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 意犹WEB前端
host: silentcloud.github.io
desc: Love Life , Love Web Design !!!

custom:
    category:
        default: Default Category
        another: Another Category
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

meta:
    author:
        name: silentcloud
        email: rjmuqiang@gmail.com
        disqus: moonka              # Disqus缩略标识
        gcse: 013497059085441911199:xlyghnoxde4     # Google自定义搜索标识ID
        github: silentcloud                         # GitHub账号
        gravatar: 9ba9d533a6bb5553c398234b5d2439ba  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
